#! /bin/bash

REGISTRY=registry.com:5000

[[ -f scribed.tar.gz ]] && echo "scribed.tar.gz exists" || cp ../scribed.tar.gz .
docker build -t nodejs:base .
docker tag nodejs:base ${REGISTRY}/nodejs:base
docker push ${REGISTRY}/nodejs:base

