#! /bin/bash

REGISTRY=registry.com:5000
NAME=nginxphp:super

[[ -f scribed.tar.gz ]] && echo "scribed.tar.gz exists" || cp ../scribed.tar.gz .
docker build -t $NAME .
docker tag $NAME ${REGISTRY}/$NAME
docker push ${REGISTRY}/$NAME

